version: '3'
services:
  nginx:
        image: nginx:1.17.9-alpine
        container_name: nginx
        volumes:
          - ./:/etc/nginx/conf.d/
        ports:
          - 80:80
          - 443:443